import React from 'react'

const props={
    'dwmc': '单位名称',
    'cs': '所在城市',
    'fddbr':  '法定代表人',
    'dzhi':  '办公地址',
    'sjlzxsbwh':  '省管理中心上报文号',
    'zcdz':  '注册地址',
    'sglzxsbsj':  '省管理中心上报时间',
    'zjpzsj':  '总局批准时间',
    'yzbm': '邮政编码',
    'zjpzwh': '总局批准文号',
    'czhen':  '传真',
    'dhua': '电话',
    'szyx':  '所长邮箱',
    'txyxming':  '通讯员姓名',
    'xtyyx':  '通讯员邮箱',
    'xtyphone':  '通讯员手机',
    'zsbh': '证书编号',
    'zczj':  '注册资金',
    'jyfw': '经营范围',
    'zrs': '总人数',
    'swsxz': '机构性质',
    'szphone': '所长手机',
    'gsyhmcbh': '工商预核名称编号',
    'dzyj': '电子邮件',
    'yhdw': '预核单位',
    'yhsj': '预核时间',
    'gzbh': '公证编号',
    'gzdw': '公证单位',
    'gzry': '公证员',
    'gzsj': '公证时间',
    'yzbh': '验资编号',
    'yzdw': '验资单位',
    'yzry': '验资人员',
    'yzsj': '验资时间',
    'tthybh': '团体会员注册号',
    'rhsj': '入会时间',
    'khh': '开户行',
    'khhzh': '开户行帐号',
    'fj': '附件',
    'swdjhm': '税务登记号码',
    'jbqk': '情况简介',
    'glzd': '事务所内部管理制度', 
    'gddh': '第一次股东会决议',
    'bgcszczm': '办公场所的产权或使用权证明', 
    'wangzhi':'事物所网址',
    'yyzzhm':'营业执照号',
    'jgdmzh':'机构代码证号',
  }
  

  module.exports = props